auth_magic: xoSS669vCJlBMh6lMsKI5VWfD4Rki3RF
password_hash_algos: sha256
shop_name: バレエショップtiara
force_ssl: 1
admin_allow_host: null
cookie_lifetime: 0
cookie_name: eccube
locale: ja
timezone: Asia/Tokyo
pageinrange: false
eccube_install: 1
