<?php
/*
 * Copyright(c) 2015 GMO Payment Gateway, Inc. All rights reserved.
 * http://www.gmo-pg.com/
 */

namespace Plugin\TransportCSVexportB2\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ModuleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransportCSVexportB2DelivTypeRepository extends EntityRepository
{
    public function getDelivList()
    {
        $query = $this->createQueryBuilder('m')
            ->select(array('m.id','m.name'))
            ->orderBy('m.rank')
            ->getQuery()
            ->getArrayResult();
        return $query;
    }
}
